INSERT INTO ROLE(ID, NAME) VALUES (1, 'TRAINING_CREATE');
INSERT INTO ROLE(ID, NAME) VALUES (2, 'TRAINING_READ');
INSERT INTO ROLE(ID, NAME) VALUES (3, 'TRAINING_UPDATE');
INSERT INTO ROLE(ID, NAME) VALUES (4, 'TRAINING_DELETE');