CREATE TABLE TRAINING
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    START DATETIME,
    TIME BIGINT,
    DISTANCE DOUBLE,
    USER_ID BIGINT
);

ALTER TABLE TRAINING ADD CONSTRAINT TRAININGS_USER
   FOREIGN KEY (USER_ID) REFERENCES USER;


